import { Translation } from './types';

export const PersianTranslation: Translation = {
  appName: "ایکس ری مالتی تست",
  currentCoreVersion: "نسخه فعلی هسته: ",
  latestCoreVersion: "آخرین نسخه منتشر شده: ",
  checkVersionBtn: "بررسی نسخه جدید هسته",
  downloadCoreBtn: "دانلود و بروزرسانی هسته",
  selectConfigTitle: "وارد کردن کانفیگ‌ها",
  importClipboard: "وارد کردن از کلیپ‌بورد",
  importFile: "وارد کردن از فایل متنی",
  importSubLink: "دریافت از لینک اشتراک",
  subUrlPlaceholder: "آدرس لینک اشتراک را وارد کنید",
  runTestsBtn: "شروع تمام تست‌ها",
  testResultsTitle: "نتایج ارزیابی",
  tcpPingLabel: "تأخیر TCP",
  jitterLabel: "جیتر (نوسان تأخیر)",
  realDelayLabel: "تأخیر واقعی (HTTP)",
  downloadSpeedLabel: "سرعت دانلود",
  uploadSpeedLabel: "سرعت آپلود",
  websiteCheckLabel: "بررسی سایت‌های منتخب",
  statusChecking: "در حال تست...",
  statusSuccess: "موفق",
  statusFailed: "خطا",
  exportHealthyBtn: "کپی کانفیگ‌های سالم",
  copySuccessMsg: "کانفیگ‌های سالم با موفقیت کپی شدند!",
  settingsTitle: "شخصی‌سازی تنظیمات",
  localSocksPort: "پورت محلی SOCKS",
  testTimeout: "زمان انتظار تست (میلی‌ثانیه)",
  customDomains: "سایت‌های تست دسترسی",
  languageBtn: "تغییر زبان (EN)",
  unknown: "نامشخص",
  progressDownloading: "در حال دانلود هسته...",
  progressExtracting: "در حال استخراج باینری...",
  fragmentSettings: "پیکربندی فرگمنت (مبارزه با ممیزی SNI)",
  enableFragment: "فعالسازی فرگمنت ترافیکی",
  fragmentLength: "طول بازه بایت‌های فرگمنت",
  fragmentInterval: "میزان تأخیر بین فرگمنت‌ها (ms)",
  muxSettings: "پیکربندی چندگانه‌سازی (Mux / XUDP)",
  enableMux: "فعالسازی مالتی‌پلکسر ترافیک",
  muxConcurrency: "حداکثر کانکشن‌های همزمان TCP",
  xudpConcurrencyLabel: "همزمانی تونل‌های XUDP",
  tlsFingerprint: "شبیه‌ساز اثر انگشت uTLS",

  // Added Persian Translations
  testProfileLabel: "پروفایل تنظیمات تست",
  profileUltra: "برق‌آسا (گیمینگ و زنده)",
  profileBalanced: "متعادل (پیش‌فرض)",
  profileStable: "دقیق و پایدار (بار سنگین)",
  profileCustom: "سفارشی (کاستوم)",
  pingCountLabel: "تعداد پینگ‌های جیتر (دفعات)",
  speedVolumeLabel: "حجم دانلود تستی (مگابایت)",
  speedProtocolLabel: "پروتکل تست سرعت",
  fragmentProfileLabel: "پروفایل فرگمنت ترافیکی",
  fragmentMci: "همراه اول (بای‌پَس استاندارد)",
  fragmentMtn: "ایرانسل شدید (بایت‌های بسیار ریز)",
  fragmentTcp: "تقسیم‌بندی TCP (فوق‌پایدار)",
  fragmentCustom: "سفارشی (کاستوم)",
  copyAllConfigs: "کپی تمام کانفیگ‌های سالم",
  copyLimitedConfigs: "کپی تعداد مشخص (تاپ رنک)",
  copyLimitCountLabel: "تعداد کانفیگ‌های برتر جهت دریافت",
  addWebsiteBtn: "افزودن وب‌سایت جدید",
  editWebsiteBtn: "ویرایش",
  deleteWebsiteBtn: "حذف",
  saveWebsiteBtn: "ذخیره",
  cancelWebsiteBtn: "لغو",
  websiteNamePlaceholder: "نام وب‌سایت (مثال: یوتیوب)",
  websiteDomainPlaceholder: "دامنه آدرس (مثال: youtube.com)",
};

export const EnglishTranslation: Translation = {
  appName: "Xray Multi Test",
  currentCoreVersion: "Current Core Version: ",
  latestCoreVersion: "Latest Available Version: ",
  checkVersionBtn: "Check for Core Update",
  downloadCoreBtn: "Download & Install Core",
  selectConfigTitle: "Import Configurations",
  importClipboard: "Import from Clipboard",
  importFile: "Import from Text File",
  importSubLink: "Import from Sub Link",
  subUrlPlaceholder: "Enter Subscription URL",
  runTestsBtn: "Start Diagnostics",
  testResultsTitle: "Diagnostics Report",
  tcpPingLabel: "TCP Ping",
  jitterLabel: "Jitter",
  realDelayLabel: "Real Delay (HTTP)",
  downloadSpeedLabel: "Download Speed",
  uploadSpeedLabel: "Upload Speed",
  websiteCheckLabel: "Website Reachability",
  statusChecking: "Testing...",
  statusSuccess: "Success",
  statusFailed: "Failed",
  exportHealthyBtn: "Copy Healthy Configs",
  copySuccessMsg: "Healthy configs copied successfully!",
  settingsTitle: "Custom Settings",
  localSocksPort: "Local SOCKS Port",
  testTimeout: "Test Timeout (ms)",
  customDomains: "Test Websites",
  languageBtn: "Switch Language (FA)",
  unknown: "Unknown",
  progressDownloading: "Downloading core...",
  progressExtracting: "Extracting binary...",
  fragmentSettings: "Fragment Slicing (Anti-SNI Blocking)",
  enableFragment: "Enable Traffic Fragmentation",
  fragmentLength: "Fragment Length (bytes)",
  fragmentInterval: "Fragment Delay (ms)",
  muxSettings: "Multiplexing Config (Mux / XUDP)",
  enableMux: "Enable Traffic Multiplexing",
  muxConcurrency: "Max TCP Concurrency",
  xudpConcurrencyLabel: "XUDP Concurrency Limit",
  tlsFingerprint: "TLS uTLS Fingerprint Simulator",

  // Added English Translations
  testProfileLabel: "Test Settings Profile",
  profileUltra: "Ultra Fast (Gaming & Real-time)",
  profileBalanced: "Balanced (Default)",
  profileStable: "Deep & Stable (Heavy Load)",
  profileCustom: "Custom (Manual Parameters)",
  pingCountLabel: "Jitter Ping Count",
  speedVolumeLabel: "Speed Test Volume (MB)",
  speedProtocolLabel: "Speed Test Protocol",
  fragmentProfileLabel: "Traffic Fragment Profile",
  fragmentMci: "MCI Bypass (Standard)",
  fragmentMtn: "Irancell Aggressive (Microbytes)",
  fragmentTcp: "TCP Slicing (Ultra Stable)",
  fragmentCustom: "Custom (Manual Slices)",
  copyAllConfigs: "Copy All Healthy Configs",
  copyLimitedConfigs: "Copy Specified Count (Top Rank)",
  copyLimitCountLabel: "Number of Top Configs to Copy",
  addWebsiteBtn: "Add New Website",
  editWebsiteBtn: "Edit",
  deleteWebsiteBtn: "Delete",
  saveWebsiteBtn: "Save",
  cancelWebsiteBtn: "Cancel",
  websiteNamePlaceholder: "Website Name (e.g. Telegram)",
  websiteDomainPlaceholder: "Domain URL (e.g. telegram.org)",
};
